language: ruby
rvm:
  - 2.4.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
cache: bundler
sudo: false
before_script:
  - "bundle exec rake db:schema:load"
  - "cp config/secrets.yml.sample config/secrets.yml"
script: "bundle exec rspec"
notifications:
  email:
    recipients:
      - rubycorns@googlegroups.com
